export T getDescriptorFromHandle<T>(DescriptorHandle<T> handle) where T : IOpaqueDescriptor
{
    return defaultGetDescriptorFromHandle(handle, BindlessDescriptorOptions::None);
}

static const float2 QUAD_POSITION[4] =
{
    float2(-1.0, -1.0),
    float2(-1.0,  1.0),
    float2( 1.0, -1.0),
    float2( 1.0,  1.0)
};

static const float2 QUAD_TEXCOORD0[4] =
{
    float2(0.0, 1.0),
    float2(0.0, 0.0),
    float2(1.0, 1.0),
    float2(1.0, 0.0)
};

static const uint QUAD_INDEX[6] =
{
    0u, 1u, 2u,
    1u, 3u, 2u
};
